'''
The different satellites require different software and configuration.
This is a pipeline-based solution. "Pipeline" is a script which is responsible
for the signal reception and its decoding.

Each pipeline takes three parameters:

* Working directory - it is writable, clean and temporary directory.
* Frequency - transmission frequency in MHz
* Duration - after this time script should stop SDR, in seconds

As output the script returns a dictionary where key is a category
and value is a path or paths to file(s). Currently the following categories
are supported:
- "signal" for initial audio file in WAV format
- "product" for decoded image
- "log" for detailed decoding notes

In the future additional categories will be added. Most likely there will be:
- "waterfall" presenting the frequency spectrum changing over time
- "telemetry" for any decoded telemetry data

Other categories are likely to appear.

User should have a possibility to execute pipeline in stand alone mode, i.e. without
the whole station code (without any need to initialize the station).

Pipeline isn't responsible for clean up. The working directory should be deleted
after file processing. If some files should be kept, then they should be moved
to a safe place.

User has a possibility to select pipeline by "pipeline" parameter in satellite
config. Now it is optional and script try to deduce pipeline based on satellite.
(For example if pipeline isn't provided and name starts with NOAA then we use
pipeline for NOAA).

All pipelines must be located in directory with this file ("pipelines") and have
"execute" method which accept all parameters.
'''

import datetime
import os
import sys
import logging
from typing import Iterable, List, Tuple

from utils.models import SatelliteConfiguration
from pipelines import pipelines
from utils.configuration import open_config
from metadata import Metadata

if sys.version_info[0] == 3 and sys.version_info[1] >= 8:
    from typing import Literal
else:
    from typing_extensions import Literal


# Categories of result the reception
# Signal - recorded signal (recommended in WAV file)
# Product - binary file decoded from signal (now it is always PNG file)
# Log - logs generated by various tools, such as rx_fm or svarog.
ReceptionResultCategory = Literal["signal", "product", "log"]


def setup_base_dir():
    config = open_config()
    base_dir = config.get("obsdir")
    if base_dir is None:
        base_dir = "/tmp/observations_tmp"
    os.makedirs(base_dir, exist_ok=True)
    return base_dir


def get_pipeline(sat: SatelliteConfiguration):
    '''
    Returns path to pipeline file assigned with the specified satellite.
    If pipeline doesn't exist throw LookupError.

    Function check "pipeline" field in passed configuration for pipeline.
    If it is empty then check built-in list with compatible pipelines.

    sat contains a dictionary with the whole configuration, including fields:
    freq, name, pipeline, save_to_disk, submit, aos_at, max_elevation, disabled
    '''

    pipeline = None
    if "pipeline" in sat:
        pipeline = sat["pipeline"]
    elif "recipe" in sat:  # Backward compatibility
        pipeline = sat["recipe"]
    if pipeline is None and sat["name"].startswith("NOAA"):
        pipeline = "noaa-apt"
    if pipeline is None:
        raise LookupError(f"Pipeline not specified. Please update your entry for satellite {sat['name']} in config.yml, e.g. add 'pipeline: satdump'")

    if not pipeline in pipelines:
        raise LookupError(f"Pipeline {pipeline} not found. Supported pipelines are {', '.join(pipelines.keys())}.")

    return pipelines[pipeline], pipeline


def get_unique_dir(sat: SatelliteConfiguration, los: datetime.datetime) -> str:
    '''
    Generates unique, but meaningful dir name.
    '''
    return los.strftime("%Y-%m-%d-%H%M") + "-" + sat["name"].lower().replace(" ", "-")


def get_dir(sat: SatelliteConfiguration, los: datetime.datetime) -> str:
    base_dir = setup_base_dir()

    reception_dir = os.path.join(base_dir, get_unique_dir(sat, los))
    os.makedirs(reception_dir, exist_ok=True)

    return reception_dir


def execute_pipeline(sat: SatelliteConfiguration, los: datetime.datetime, metadata: Metadata) \
        -> Tuple[Iterable[Tuple[ReceptionResultCategory, str]], str, Metadata]:
    '''
    Execute pipeline for specified satellite and return results.

    Return collection of tuples with category, path, and updated metadata.
    Second item in result is path to temporary observation directory.
    If no pipeline found then throw LookupError.

    We use "signal" category for raw, unprocessed received signal file
    and "product" for finished data (e. q. imagery) extracted from signal.
    You may get multiple files with the same category.

    Caller is responsible for cleaning up the results.
    You need delete or move returned files when you don't need them. You should
    also delete the temporary observation directory.
    '''
    pipeline_function, pipeline_name = get_pipeline(sat)

    reception_dir = get_dir(sat, los)
    now = datetime.datetime.now(datetime.timezone.utc)
    record_interval = los - now

    if record_interval < datetime.timedelta(minutes=0):
        logging.error("Invalid record interval (now is {now}, LOS is {los}, delta is {record_interval.total_seconds()} seconds)")
        raise ValueError(f"Invalid record interval (now is {now}, LOS is {los}, delta is {record_interval.total_seconds()} seconds)")

    # Add pipeline-specific metadata to the existing metadata object
    metadata.set("frequency", sat["freq"])
    metadata.set("pipeline", str(pipeline_name))
    # Keep backward compatibility
    metadata.set("recipe", str(pipeline_name))

    # Pass custom command if specified
    custom_command = sat.get("custom_command")
    if custom_command:
        metadata.set("custom_command", custom_command)

    output = pipeline_function(reception_dir, sat["freq"], record_interval, metadata, custom_command)
    return output, reception_dir, metadata


def get_pipeline_names() -> List[str]:
    '''Returns all pipeline names.'''
    return list(pipelines.keys())

def get_recipe_names() -> List[str]:
    '''Returns all recipe names (backward compatibility).'''
    return get_pipeline_names()
